{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "analyzercore.fullname" . }}-secrets
  labels:
    {{- include "analyzercore.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwt.secret | quote }}
  JWT_ISSUER: {{ .Values.secrets.jwt.issuer | quote }}
  JWT_AUDIENCE: {{ .Values.secrets.jwt.audience | quote }}
{{- end }}
