apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analyzercore-data
  namespace: analyzercore
  labels:
    app.kubernetes.io/name: analyzercore
    app.kubernetes.io/component: api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
